import {
  AlertCircle,
  AlertTriangle,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  ArrowLeft,
  ArrowRight,
  BadgePercent,
  Banknote,
  Bell,
  Bold,
  Briefcase,
  Calendar,
  CalendarDays,
  CalendarRange,
  ChartColumn,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  ChevronUp,
  Clock,
  CloudUpload,
  Code,
  Download,
  Eraser,
  Eye,
  EyeOff,
  FileDown,
  FileSearch,
  FileUp,
  Filter,
  Handshake,
  Heading1,
  Heading2,
  Heart,
  Home,
  Image,
  Inbox,
  Info,
  Italic,
  Key,
  Landmark,
  LayoutGrid,
  Link,
  List,
  ListOrdered,
  Loader2,
  LogOut,
  type LucideProps,
  Mail,
  Minus,
  Moon,
  MoreVertical,
  Package,
  PanelLeftClose,
  PanelRightClose,
  Pencil,
  Phone,
  Pilcrow,
  Plus,
  Printer,
  Quote,
  Redo,
  Search,
  Settings,
  ShieldCheck,
  ShoppingCart,
  SlidersVertical,
  SquarePen,
  Star,
  Store,
  Strikethrough,
  Sun,
  Trash2,
  TrendingUp,
  Trophy,
  Underline,
  Undo,
  Unlink,
  Upload,
  User,
  Users,
  Video,
  Wallet,
  X,
  XCircle,
} from 'lucide-react';
import type { CSSProperties, FC } from 'react';

export type IconProps = {
  className?: string;
  style?: CSSProperties;
  strokeWidth?: number;
};

export type Icon = FC<IconProps>;

const iconMap = {
  heart: Heart,
  home: Home,
  'home-solid': Home,
  /** Alias matching the exact icon name in docs/design/p4-product-manager-design.html (Section A · Icon set) */
  dashboard: Home,
  product: Package,
  order: FileSearch,
  category: LayoutGrid,
  coupon: BadgePercent,
  refund: Undo,
  cart: ShoppingCart,
  edit: SquarePen,
  close: X,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  back: ArrowLeft,
  upload: Upload,
  filter: Filter,
  star: Star,
  more: MoreVertical,
  trend: TrendingUp,
  logout: LogOut,
  /** P4 menu aliases (replaces libraries/icons on web) */
  add: Plus,
  briefcase: Briefcase,
  graph: ChartColumn,
  frame: LayoutGrid,
  'receipt-search': FileSearch,
  'arrow-up-tray': Upload,
  'arrow-up-tray-solid': Upload,
  loading: Loader2,
  'magnifying-glass': Search,
  envelope: Mail,
  key: Key,
  phone: Phone,
  'check-circle': CheckCircle,
  eye: Eye,
  'eye-slash': EyeOff,
  check: Check,
  'check-v2': Check,
  minus: Minus,
  moon: Moon,
  trash: Trash2,
  'trash-solid': Trash2,
  'exclamation-triangle': AlertTriangle,
  'exclamation-circle': AlertCircle,
  'x-mark': X,
  'x-circle': XCircle,
  'vuesax-arrow-down': ChevronDown,
  'vuesax-arrow-up': ChevronUp,
  'vuesax-arrow-left': ChevronLeft,
  'vuesax-arrow-right': ChevronRight,
  'caret-down-fill': ChevronDown,
  'caret-up-fill': ChevronUp,
  inbox: Inbox,
  'chevron-double-left': ChevronsLeft,
  'chevron-double-right': ChevronsRight,
  'cloud-arrow-up': CloudUpload,
  user: User,
  'chevron-down': ChevronDown,
  calendar: Calendar,
  'calendar-solid': Calendar,
  'calendar-days': CalendarDays,
  'calendar-days-solid': CalendarDays,
  'calendar-date-range': CalendarRange,
  'calendar-date-range-solid': CalendarRange,
  clock: Clock,
  'clock-solid': Clock,
  undo: Undo,
  redo: Redo,
  bold: Bold,
  italic: Italic,
  underline: Underline,
  strikethrough: Strikethrough,
  code: Code,
  link: Link,
  'link-off': Unlink,
  h1: Heading1,
  h2: Heading2,
  paragraph: Pilcrow,
  list: List,
  'list-ordered': ListOrdered,
  ul: List,
  ol: ListOrdered,
  left: AlignLeft,
  center: AlignCenter,
  right: AlignRight,
  justify: AlignJustify,
  menu: AlignJustify,
  search: Search,
  eraser: Eraser,
  image: Image,
  video: Video,
  quote: Quote,
  pencil: Pencil,
  'pencil-square': SquarePen,
  'vuesax-element': LayoutGrid,
  'user-group': Users,
  users: Users,
  'building-storefront': Store,
  'vuesax-empty-wallet-change': Wallet,
  'vuesax-money-receive': Banknote,
  'collapse-left': PanelLeftClose,
  'collapse-right': PanelRightClose,
  bell: Bell,
  'adjustments-vertical': SlidersVertical,
  'ellipsis-vertical': MoreVertical,
  plus: Plus,
  'information-circle': Info,
  'arrow-down-tray': Download,
  printer: Printer,
  'vuesax-document-upload': FileUp,
  'vuesax-document-download': FileDown,
  trophy: Trophy,
  handshake: Handshake,
  landmark: Landmark,
  package: Package,
  settings: Settings,
  'shield-check': ShieldCheck,
  'arrow-right': ArrowRight,
  'shopping-cart': ShoppingCart,
  sun: Sun,
  'log-out': LogOut,
} satisfies Record<string, FC<LucideProps>>;

export type IconName = keyof typeof iconMap;

export const RenderIcon = ({
  name,
  className,
  style,
  strokeWidth,
}: IconProps & { name?: IconName }) => {
  if (!name) return null;
  const Icon = iconMap[name];
  if (!Icon) return null;

  const isLoading = name === 'loading';

  return (
    <Icon
      className={className}
      style={{ width: 20, height: 20, ...style }}
      strokeWidth={strokeWidth}
      {...(isLoading ? { 'data-loading': true } : {})}
    />
  );
};
