/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  theme: {
    extend: {
      lineHeight: {
        64: 'var(--lineHeight-64)',
        56: 'var(--lineHeight-56)',
        48: 'var(--lineHeight-48)',
        40: 'var(--lineHeight-40)',
        32: 'var(--lineHeight-32)',
        24: 'var(--lineHeight-24)',
        20: 'var(--lineHeight-20)',
        16: 'var(--lineHeight-16)',
        12: 'var(--lineHeight-12)',
      },
      boxShadow: {
        md: '0px 8px 12px rgba(234, 88, 12, 0.12)',
        border: '0px 0px 0px 1px rgba(234, 88, 12, 1), 0px 0px 0px 2px rgba(234, 88, 12, 0.2)',
        'focus-ring': '0 0 0 3px var(--color-primary-focus-ring)',
      },
    },
    colors: {
      inherit: 'inherit',
      transparent: 'transparent',
      current: 'currentColor',
      white: '#ffffff',
      black: '#000000',
      primary: {
        DEFAULT: 'var(--color-primary)',
        background: 'var(--color-primary-bg)',
        hover: 'var(--color-primary-hover)',
        base: 'var(--color-primary-base)',
        clicked: 'var(--color-primary-clicked)',
        border: 'var(--color-primary-border)',
      },
      secondary: {
        DEFAULT: 'var(--color-secondary)',
        background: 'var(--color-secondary-bg)',
        hover: 'var(--color-secondary-hover)',
        base: 'var(--color-secondary-base)',
        clicked: 'var(--color-secondary-clicked)',
        border: 'var(--color-secondary-border)',
      },
      neutral: {
        DEFAULT: 'var(--color-neutral)',
        white: 'var(--color-neutral-white)',
        'table-header': 'var(--color-neutral-table-header)',
        bg: 'var(--color-neutral-bg)',
        divider: 'var(--color-neutral-divider)',
        disable: 'var(--color-neutral-disable)',
        border: 'var(--color-neutral-border)',
        placeholder: 'var(--color-neutral-placeholder)',
        'text-secondary': 'var(--color-neutral-text-secondary)',
        'text-primary': 'var(--color-neutral-text-primary)',
        black: 'var(--color-neutral-black)',
      },
      pending: {
        DEFAULT: 'var(--color-pending)',
        bg: 'var(--color-pending-bg)',
        hover: 'var(--color-pending-hover)',
        base: 'var(--color-pending-base)',
        clicked: 'var(--color-pending-clicked)',
        border: 'var(--color-pending-border)',
      },
      error: {
        DEFAULT: 'var(--color-error)',
        bg: 'var(--color-error-bg)',
        hover: 'var(--color-error-hover)',
        base: 'var(--color-error-base)',
        clicked: 'var(--color-error-clicked)',
        border: 'var(--color-error-border)',
      },
      success: {
        DEFAULT: 'var(--color-success)',
        bg: 'var(--color-success-bg)',
        hover: 'var(--color-success-hover)',
        base: 'var(--color-success-base)',
        clicked: 'var(--color-success-clicked)',
        border: 'var(--color-success-border)',
      },
      info: {
        DEFAULT: 'var(--color-info)',
        bg: 'var(--color-info-bg)',
        hover: 'var(--color-info-hover)',
        base: 'var(--color-info-base)',
        clicked: 'var(--color-info-clicked)',
        border: 'var(--color-info-border)',
      },
    },
    fontSize: {
      48: 'var(--size-48)',
      40: 'var(--size-40)',
      36: 'var(--size-36)',
      32: 'var(--size-32)',
      28: 'var(--size-28)',
      24: 'var(--size-24)',
      20: 'var(--size-20)',
      18: 'var(--size-18)',
      17: 'var(--size-17)',
      16: 'var(--size-16)',
      15: 'var(--size-15)',
      14: 'var(--size-14)',
      13: 'var(--size-13)',
      12: 'var(--size-12)',
      10: 'var(--size-10)',
      8: 'var(--size-8)',
      xs: 'var(--size-12)',
      sm: 'var(--size-14)',
      base: 'var(--size-16)',
      lg: 'var(--size-18)',
      xl: 'var(--size-20)',
      'heading-1': ['48px', '64px'],
      'heading-2': ['40px', '56px'],
      'heading-3': ['36px', '56px'],
      'heading-4': ['32px', '48px'],
      'heading-5': ['28px', '40px'],
      'title-1': ['24px', '32px'],
      'title-2': ['20px', '24px'],
      'title-3': ['18px', '24px'],
      'subhead-1': ['20px', '24px'],
      'subhead-2': ['13px', '24px'],
      'body-1': ['15px', '24px'],
      'body-2': ['13px', '24px'],
      'caption-1': ['12px', '16px'],
      'caption-2': ['10px', '16px'],
      'caption-3': ['8px', '12px'],

      /* Dense UI scale (admin/storefront app screens) — theo docs/design/p4-product-manager-design.html (Phần A · Typography) */
      'ui-stat': ['30px', { lineHeight: '38px', fontWeight: '800', letterSpacing: '-0.02em' }],
      'ui-h1': ['26px', { lineHeight: '34px', fontWeight: '800', letterSpacing: '-0.02em' }],
      'ui-h2': ['19px', { lineHeight: '26px', fontWeight: '800' }],
      'ui-h3': ['15px', { lineHeight: '20px', fontWeight: '800' }],
      'ui-body': ['13.5px', { lineHeight: '20px', fontWeight: '500' }],
      'ui-body-strong': ['13.5px', { lineHeight: '20px', fontWeight: '700' }],
      'ui-label': ['12.5px', { lineHeight: '16px', fontWeight: '700' }],
      'ui-caption': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      'ui-overline': ['11px', { lineHeight: '14px', fontWeight: '700', letterSpacing: '0.06em' }],
      'ui-mono': ['12.5px', { lineHeight: '18px', fontWeight: '700' }],
    },
    fontFamily: {
      primary: 'var(--font-primary)',
      mono: 'var(--font-mono)',
    },
  },
};
