export const LOW_STOCK_THRESHOLD = 10;

/** Keys map to language/{locale}/error.json — handler translates via i18n */
export const errorKeys = {
  unauthorized: 'unauthorized',
  forbidden: 'forbidden',
  invalidToken: 'invalid_token',
  notFound: 'not_found',
  productNotFound: 'product_not_found',
  invalidCredentials: 'invalid_credentials',
  invalidQuantity: 'invalid_quantity',
  itemsRequired: 'items_required',
  invalidPagination: 'invalid_pagination',
  cloudinaryNotConfigured: 'cloudinary_not_configured',
  uploadFileRequired: 'upload_file_required',
  uploadInvalidType: 'upload_invalid_type',
  uploadInvalidFolder: 'upload_invalid_folder',
  invalidRefreshToken: 'invalid_refresh_token',
  refreshTokenExpired: 'refresh_token_expired',
  addressRequired: 'address_required',
  addressNotFound: 'address_not_found',
  orderNotFound: 'order_not_found',
  paymentNotFound: 'payment_not_found',
  paymentAlreadyPaid: 'payment_already_paid',
  orderNotPayable: 'order_not_payable',
  shipmentNotFound: 'shipment_not_found',
  invalidShipmentStatus: 'invalid_shipment_status',
  categoryNotFound: 'category_not_found',
  couponNotFound: 'coupon_not_found',
  couponInvalid: 'coupon_invalid',
  reviewExists: 'review_exists',
  refundInvalid: 'refund_invalid',
  orderNotCancellable: 'order_not_cancellable',
  fileNotFound: 'file_not_found',
  fileStillInUse: 'file_still_in_use',
  fileDeleteFailed: 'file_delete_failed',
} as const;
